### ISSUE TITLE
关于注意事项中的对于y的处理

### ISSUE THREAD

**Issue by lingxi0** [XDZhelheim/Torch-MTS#18]
您好，请问这个关于y不进行缩放是通过理论分析还是实验分析得到的呢，有什么特殊意义么，它是怎么影响到最终的预测精度的，

**Comment by XDZhelheim** [comment]
你好，这是个关键问题。有点尴尬，我前两天刚把相关实验删了。。

首先你可以看这个文件 https://github.com/XDZhelheim/Torch-MTS/blob/v1.4/scaler_check.ipynb
还有上个版本的readme：https://github.com/XDZhelheim/Torch-MTS/blob/v1.4/README.md

对于交通预测：
简单解释一下，首先有一个大前提，那就是模型训练过程中在算loss的时候，y_pred和y_true都必须在**真实值的分布范围**而不是transform之后的标准正态分布。否则整个模型训出来就是一坨，这个可以实验证明。而且大家都是这么做的，算是个共识。

1. 有些代码的做法是，在读数据的时候创建scaler把x和y_true全都transform了。然后在算loss之前把y_true给inverse_transform回去。首先，从写代码的角度来讲，我认为但凡学过一点程序设计的都能看出来这就是个纯冗余操作。把y_true拉出来溜了一圈又回去了。所以一开始就没必要transform y，这是最主要的原因，没必要多此一举。
2. 由于浮点误差，有可能 `inverse_transform(transform(y_true)) != y_true`。然后就有可能蹦出来一些特别小的值 (然后你就发现MAPE直接几十万上百万)，不过这一块我也没能稳定复现，挺玄学。
3. 这中间还可能涉及一个float64转float32的精度丢失问题。如果原始数据(比如我这个项目里的各种data.npz)读进来是64位精度，然后transform了，这时候还是64，但是转tensor的时候，torch的floattensor都是32位精度的，这里就自动向下转型导致精度丢失。如果这时候再inverse回去，那还是32位精度，跟原来64位相比就大概率有浮点误差。

反正一开始就别动y_true，就把可能出现的奇怪情况直接扼杀了，我感觉是百利无一害。

对于长序列预测：
他们就是全程所有数据全部transform，连算metrics的时候都是transform后的状态。。所以你看他们的MAE MSE全是0.x。不知道这么做有什么意义，我反正感觉很扯淡，但是那边好像已经形成习惯了。

**Comment by lingxi0** [comment]
嗯嗯，感谢您的回答
我在自己的实验中用的是最大最小值归一化，压缩到01之间的那种，好像并没有改变数据的分布？不过这还是需要我自己的实验验证。
关于后者它们做的长序列预测，我也觉得很扯，不知道为啥不是给出反归一化之后的结果。
