### ISSUE TITLE
想问一下GMAN是否可以应用于PEMS04等数据集

### ISSUE THREAD

**Issue by sugar-hub** [XDZhelheim/Torch-MTS#20]
作者您好！

很感谢您整理了这么多Model并且能让它们能在这么多数据集上跑起来。

我发现GMAN模型只支持METRLA和PEMSBAY两个数据集，而不支持PEMS04等数据集。我猜是不是因为SE文件的缘故？只有METRLA和PEMSBAY两个数据集有这两个文件。请问像PEMS04这种没有SE文件的数据集，GMAN还能在这种数据集上跑起来吗？

**Comment by XDZhelheim** [comment]
您好，感谢您的支持。

是的，其他数据集的SE现在还没搞，所以GMAN跑不了。
请参考 issue #15 。
有空我会把各个数据集的SE文件都做一遍，然后更新GMAN的结果。

**Comment by sugar-hub** [comment]
好的，谢谢您！
